# Generated by Django 3.2.4 on 2021-06-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=700, null=True)),
                ('title', models.CharField(blank=True, max_length=700, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('done', models.BooleanField(blank=True, default=False, null=True)),
                ('delete', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
