# Generated by Django 3.2.4 on 2021-06-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='code',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
