# Generated by Django 3.2.4 on 2021-06-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
